USE `AutoRepair`;

CREATE TABLE IF NOT EXISTS `llm_model_configs` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `provider_code` VARCHAR(32) NOT NULL,
    `provider_name` VARCHAR(64) NOT NULL,
    `vendor_name` VARCHAR(64) NOT NULL,
    `model_key` VARCHAR(128) NOT NULL,
    `display_name` VARCHAR(120) NOT NULL,
    `api_model_name` VARCHAR(128) NOT NULL,
    `api_base_url` VARCHAR(512) NULL,
    `api_key_env_var` VARCHAR(64) NULL,
    `enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `is_default_chat` TINYINT(1) NOT NULL DEFAULT 0,
    `is_default_repair` TINYINT(1) NOT NULL DEFAULT 0,
    `supports_streaming` TINYINT(1) NOT NULL DEFAULT 1,
    `supports_json` TINYINT(1) NOT NULL DEFAULT 1,
    `sort_order` INT NOT NULL DEFAULT 0,
    `notes` TEXT NULL,
    `extra_config_json` LONGTEXT NULL,
    `deleted_at` DATETIME NULL DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_llm_model_configs_model_key` (`model_key`),
    KEY `idx_llm_model_configs_enabled_sort` (`enabled`, `deleted_at`, `sort_order`)
);

INSERT IGNORE INTO `llm_model_configs` (
    `provider_code`,
    `provider_name`,
    `vendor_name`,
    `model_key`,
    `display_name`,
    `api_model_name`,
    `api_base_url`,
    `api_key_env_var`,
    `enabled`,
    `is_default_chat`,
    `is_default_repair`,
    `supports_streaming`,
    `supports_json`,
    `sort_order`,
    `notes`,
    `extra_config_json`
)
VALUES
(
    'openai_compatible',
    'Qwen',
    'Alibaba Cloud',
    'qwen3.5-plus',
    'Qwen 3.5 Plus',
    'qwen3.5-plus',
    'https://dashscope.aliyuncs.com/compatible-mode/v1',
    'QWEN_API_KEY',
    1,
    1,
    0,
    1,
    1,
    10,
    'Default chat model.',
    '{}'
),
(
    'openai_compatible',
    'OpenAI',
    'OpenAI',
    'gpt-5.2',
    'GPT-5.2',
    'gpt-5.2',
    NULL,
    'OPENAI_API_KEY',
    1,
    0,
    0,
    1,
    1,
    20,
    'OpenAI flagship general-purpose model.',
    '{}'
),
(
    'gemini',
    'Gemini',
    'Google',
    'gemini-2.5-pro',
    'Gemini 2.5 Pro',
    'gemini-2.5-pro',
    NULL,
    'GEMINI_API_KEY',
    1,
    0,
    0,
    1,
    1,
    30,
    'Google Gemini reasoning model.',
    '{}'
),
(
    'openai_compatible',
    'Qwen',
    'Alibaba Cloud',
    'qwen3.5-flash',
    'Qwen 3.5 Flash',
    'qwen3.5-flash',
    'https://dashscope.aliyuncs.com/compatible-mode/v1',
    'QWEN_API_KEY',
    1,
    0,
    1,
    1,
    1,
    40,
    'Default repair model.',
    '{}'
);
